### ISSUE TITLE
.

### ISSUE THREAD

**Issue by ghost** [TedSinger/hyooze#2]

**Comment by Relaxtest2024** [comment]
My dad said I am trying to catch a big fish.
I am! If I manage to catch this fish, then I am going to earn everything that I ever wanted, maybe a position in a top institution and a lab and a startup. 
And I just need more friends at this time to pull things together. 
As much frustrated you are gone, but hopefully one day you can see the greatness of this idea.

**Comment by Relaxtest2024** [comment]
![RDT_20240508_0650492146045002777924185](https://github.com/TedSinger/hyooze/assets/168932586/71284420-9466-461f-8b4a-0616da8e09a2)
